name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') != true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mefisto94/andraste-distribution-builder:${GITHUB_SHA}

  build-tag:
    # This job runs only on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image for tag
      run: docker build . --file Dockerfile --tag mefisto94/andraste-distribution-builder:${{ github.ref_name }}
    - name: Push Docker image for tag
      run: docker push mefisto94/andraste-distribution-builder:${{ github.ref_name }}
